name: store_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.0.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  flutter_spinkit: ^5.1.0
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  pretty_dio_logger: ^1.3.1
  get: ^4.6.5
  get_it: ^7.2.0
  flutter_bloc: ^7.0.1
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh_flutter3: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  responsive_sizer: ^3.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/nav_bar/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
