/// Flutter icons TenantsIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TenantsIcons
///      fonts:
///       - asset: fonts/TenantsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TenantsIcons {
  TenantsIcons._();

  static const _kFontFam = 'TenantsIcons';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData confirm = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_service = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_round_fill = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fatorah = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forget_your_password = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData job_mans = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_outlined = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notebook = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pansa = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData register = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roman = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stepper2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stepper3 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stepper4 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trous = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verify = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warning = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData worker = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarmclock = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
